### ISSUE TITLE
read QSM from aRchi

### ISSUE THREAD

**Issue by mwsgeoeco** [aidanmorales/rTwig#14]
Hi, 
I'm trying to import a QSM from aRchi. I extracted the QSM with _get_QSM_(aRchiTree) and wrote this object in to a csv. When I try  to read this csv into rTwig, I get the following error:

> Error in `rTwig::run_rtwig()`:
> ! Unsupported QSM format provided.
> i Only TreeQSM, SimpleForest, Treegraph, or aRchi QSMs are supported.

Do you maybe have an example for how exactly a csv from aRchi should look like? 

Thanks!

**Comment by aidanmorales** [comment]
Hi @mwsgeoeco,

There is an example `aRchi` QSM as a `.csv` built into the package. You can access it with the following code: 

```r
qsm <- read.csv(system.file("extdata/QSM2.csv", package = "rTwig"))
```

If you don't want to export the data into a `.csv` at all, you can run Real Twig directly on the `aRchi` QSM, using the `correct_radii()` function from `rTwig`.  You can use the example point cloud from `rTwig` to make the QSM with `aRchi`, and then run the correction directly, or save and use the `.csv`. This was tested on `aRchi` v2.1.3. See the code below, and let me know if you have any issues.

```r
# Load rTwig example cloud
file <- system.file("extdata/cloud.txt", package = "rTwig")
cloud <- read.table(file)

# Build aRchi QSM from cloud
qsm <- aRchi::build_aRchi(point_cloud = cloud)
qsm <- aRchi::skeletonize_pc(qsm)
qsm <- aRchi::add_radius(qsm)

# Extract aRchi QSM cylinder data
cylinder <- aRchi::get_QSM(qsm)

# Run rTwig from aRchi::get_QSM()
rTwig_QSM <- rTwig::correct_radii(cylinder, twig_radius = 2)

# Temp file to test run_rtwig()
temp_file <- tempfile(pattern = "cylinder", fileext = ".csv")

# Export aRchi QSM cylinder data
write.csv(
  x = cylinder,
  file = temp_file,
  row.names = FALSE
)

# Run rTwig from .csv
rTwig_QSM2 <- rTwig::run_rtwig(
  filename = temp_file,
  twig_radius = 2,
  metrics = FALSE
)
```

**Comment by mwsgeoeco** [comment]
Thank you very much! Maybe you could add this to the readme section?
