### ISSUE TITLE
Can't run `run_rtwig` on treegraph QSM, only individual functions

### ISSUE THREAD

**Issue by thomashay** [aidanmorales/rTwig#5]
Hello there, I encountered one more slight issue. When I run `run_rtwig` on my treegraph QSM, I get the error:
```
...
Generating Branch Paths
Starting Workers
Correcting Branch Paths
Closing Workers
Updating Cylinder Radii
Error: argument "branch_alt" is missing, with no default
```
However, I can run all of the rTwig functions individually on this same QSM, only in this combined/wrapper `run_rtwig` function I get problems. You can find the QSM here if you want to test yourself: https://owncloud.gwdg.de/index.php/s/xdZnOQPG5LJZmGD

Best regards!

**Comment by aidanmorales** [comment]
Thanks for catching this. It turns out I forgot to add branch_alt to tree metrics calculations for Treegraph. Please try out the latest development version with devtools::install_github("aidanmorales/rTwig"), as this should now be fixed.

**Comment by thomashay** [comment]
Thanks for the again very quick fix! Great to see this amazing support!
